{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Temperature: 29.00°C\n",
      "Pressure: 1003 hPa\n",
      "Humidity: 78%\n",
      "Description: overcast clouds\n",
      "Wind Speed: 4.97 m/s\n",
      "Temperature: 29.00°C\n",
      "Pressure: 1003 hPa\n",
      "Humidity: 78%\n",
      "Description: overcast clouds\n",
      "Wind Speed: 4.97 m/s\n",
      "Temperature: 29.00°C\n",
      "Pressure: 1003 hPa\n",
      "Humidity: 78%\n",
      "Description: overcast clouds\n",
      "Wind Speed: 4.97 m/s\n",
      "Temperature: 29.00°C\n",
      "Pressure: 1003 hPa\n",
      "Humidity: 78%\n",
      "Description: overcast clouds\n",
      "Wind Speed: 4.97 m/s\n",
      "Temperature: 29.00°C\n",
      "Pressure: 1003 hPa\n",
      "Humidity: 78%\n",
      "Description: overcast clouds\n",
      "Wind Speed: 4.97 m/s\n",
      "Temperature: 29.00°C\n",
      "Pressure: 1003 hPa\n",
      "Humidity: 78%\n",
      "Description: overcast clouds\n",
      "Wind Speed: 4.97 m/s\n",
      "Temperature: 29.00°C\n",
      "Pressure: 1003 hPa\n",
      "Humidity: 78%\n",
      "Description: overcast clouds\n",
      "Wind Speed: 4.97 m/s\n",
      "Temperature: 29.00°C\n",
      "Pressure: 1003 hPa\n",
      "Humidity: 78%\n",
      "Description: overcast clouds\n",
      "Wind Speed: 4.97 m/s\n"
     ]
    },
    {
     "ename": "ConnectionError",
     "evalue": "HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?q=Hanoi,VN&appid=0706188be46c52e0136e9007e8e727d6 (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x0000026A8D75F220>: Failed to resolve 'api.openweathermap.org' ([Errno 11001] getaddrinfo failed)\"))",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mgaierror\u001b[0m                                  Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\urllib3\\connection.py:203\u001b[0m, in \u001b[0;36mHTTPConnection._new_conn\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    202\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 203\u001b[0m     sock \u001b[39m=\u001b[39m connection\u001b[39m.\u001b[39;49mcreate_connection(\n\u001b[0;32m    204\u001b[0m         (\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_dns_host, \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mport),\n\u001b[0;32m    205\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mtimeout,\n\u001b[0;32m    206\u001b[0m         source_address\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msource_address,\n\u001b[0;32m    207\u001b[0m         socket_options\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msocket_options,\n\u001b[0;32m    208\u001b[0m     )\n\u001b[0;32m    209\u001b[0m \u001b[39mexcept\u001b[39;00m socket\u001b[39m.\u001b[39mgaierror \u001b[39mas\u001b[39;00m e:\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\urllib3\\util\\connection.py:60\u001b[0m, in \u001b[0;36mcreate_connection\u001b[1;34m(address, timeout, source_address, socket_options)\u001b[0m\n\u001b[0;32m     58\u001b[0m     \u001b[39mraise\u001b[39;00m LocationParseError(\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m'\u001b[39m\u001b[39m{\u001b[39;00mhost\u001b[39m}\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m, label empty or too long\u001b[39m\u001b[39m\"\u001b[39m) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[1;32m---> 60\u001b[0m \u001b[39mfor\u001b[39;00m res \u001b[39min\u001b[39;00m socket\u001b[39m.\u001b[39;49mgetaddrinfo(host, port, family, socket\u001b[39m.\u001b[39;49mSOCK_STREAM):\n\u001b[0;32m     61\u001b[0m     af, socktype, proto, canonname, sa \u001b[39m=\u001b[39m res\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\socket.py:955\u001b[0m, in \u001b[0;36mgetaddrinfo\u001b[1;34m(host, port, family, type, proto, flags)\u001b[0m\n\u001b[0;32m    954\u001b[0m addrlist \u001b[39m=\u001b[39m []\n\u001b[1;32m--> 955\u001b[0m \u001b[39mfor\u001b[39;00m res \u001b[39min\u001b[39;00m _socket\u001b[39m.\u001b[39;49mgetaddrinfo(host, port, family, \u001b[39mtype\u001b[39;49m, proto, flags):\n\u001b[0;32m    956\u001b[0m     af, socktype, proto, canonname, sa \u001b[39m=\u001b[39m res\n",
      "\u001b[1;31mgaierror\u001b[0m: [Errno 11001] getaddrinfo failed",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[1;31mNameResolutionError\u001b[0m                       Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py:790\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)\u001b[0m\n\u001b[0;32m    789\u001b[0m \u001b[39m# Make the request on the HTTPConnection object\u001b[39;00m\n\u001b[1;32m--> 790\u001b[0m response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_make_request(\n\u001b[0;32m    791\u001b[0m     conn,\n\u001b[0;32m    792\u001b[0m     method,\n\u001b[0;32m    793\u001b[0m     url,\n\u001b[0;32m    794\u001b[0m     timeout\u001b[39m=\u001b[39mtimeout_obj,\n\u001b[0;32m    795\u001b[0m     body\u001b[39m=\u001b[39mbody,\n\u001b[0;32m    796\u001b[0m     headers\u001b[39m=\u001b[39mheaders,\n\u001b[0;32m    797\u001b[0m     chunked\u001b[39m=\u001b[39mchunked,\n\u001b[0;32m    798\u001b[0m     retries\u001b[39m=\u001b[39mretries,\n\u001b[0;32m    799\u001b[0m     response_conn\u001b[39m=\u001b[39mresponse_conn,\n\u001b[0;32m    800\u001b[0m     preload_content\u001b[39m=\u001b[39mpreload_content,\n\u001b[0;32m    801\u001b[0m     decode_content\u001b[39m=\u001b[39mdecode_content,\n\u001b[0;32m    802\u001b[0m     \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mresponse_kw,\n\u001b[0;32m    803\u001b[0m )\n\u001b[0;32m    805\u001b[0m \u001b[39m# Everything went great!\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py:496\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[1;34m(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)\u001b[0m\n\u001b[0;32m    495\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 496\u001b[0m     conn\u001b[39m.\u001b[39;49mrequest(\n\u001b[0;32m    497\u001b[0m         method,\n\u001b[0;32m    498\u001b[0m         url,\n\u001b[0;32m    499\u001b[0m         body\u001b[39m=\u001b[39;49mbody,\n\u001b[0;32m    500\u001b[0m         headers\u001b[39m=\u001b[39;49mheaders,\n\u001b[0;32m    501\u001b[0m         chunked\u001b[39m=\u001b[39;49mchunked,\n\u001b[0;32m    502\u001b[0m         preload_content\u001b[39m=\u001b[39;49mpreload_content,\n\u001b[0;32m    503\u001b[0m         decode_content\u001b[39m=\u001b[39;49mdecode_content,\n\u001b[0;32m    504\u001b[0m         enforce_content_length\u001b[39m=\u001b[39;49menforce_content_length,\n\u001b[0;32m    505\u001b[0m     )\n\u001b[0;32m    507\u001b[0m \u001b[39m# We are swallowing BrokenPipeError (errno.EPIPE) since the server is\u001b[39;00m\n\u001b[0;32m    508\u001b[0m \u001b[39m# legitimately able to close the connection after sending a valid response.\u001b[39;00m\n\u001b[0;32m    509\u001b[0m \u001b[39m# With this behaviour, the received response is still readable.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\urllib3\\connection.py:395\u001b[0m, in \u001b[0;36mHTTPConnection.request\u001b[1;34m(self, method, url, body, headers, chunked, preload_content, decode_content, enforce_content_length)\u001b[0m\n\u001b[0;32m    394\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mputheader(header, value)\n\u001b[1;32m--> 395\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mendheaders()\n\u001b[0;32m    397\u001b[0m \u001b[39m# If we're given a body we start sending that in chunks.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\http\\client.py:1271\u001b[0m, in \u001b[0;36mHTTPConnection.endheaders\u001b[1;34m(self, message_body, encode_chunked)\u001b[0m\n\u001b[0;32m   1270\u001b[0m     \u001b[39mraise\u001b[39;00m CannotSendHeader()\n\u001b[1;32m-> 1271\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_send_output(message_body, encode_chunked\u001b[39m=\u001b[39;49mencode_chunked)\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\http\\client.py:1031\u001b[0m, in \u001b[0;36mHTTPConnection._send_output\u001b[1;34m(self, message_body, encode_chunked)\u001b[0m\n\u001b[0;32m   1030\u001b[0m \u001b[39mdel\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_buffer[:]\n\u001b[1;32m-> 1031\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msend(msg)\n\u001b[0;32m   1033\u001b[0m \u001b[39mif\u001b[39;00m message_body \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m   1034\u001b[0m \n\u001b[0;32m   1035\u001b[0m     \u001b[39m# create a consistent interface to message_body\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\http\\client.py:969\u001b[0m, in \u001b[0;36mHTTPConnection.send\u001b[1;34m(self, data)\u001b[0m\n\u001b[0;32m    968\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mauto_open:\n\u001b[1;32m--> 969\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconnect()\n\u001b[0;32m    970\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\urllib3\\connection.py:243\u001b[0m, in \u001b[0;36mHTTPConnection.connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    242\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mconnect\u001b[39m(\u001b[39mself\u001b[39m) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m--> 243\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msock \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_new_conn()\n\u001b[0;32m    244\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_tunnel_host:\n\u001b[0;32m    245\u001b[0m         \u001b[39m# If we're tunneling it means we're connected to our proxy.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\urllib3\\connection.py:210\u001b[0m, in \u001b[0;36mHTTPConnection._new_conn\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    209\u001b[0m \u001b[39mexcept\u001b[39;00m socket\u001b[39m.\u001b[39mgaierror \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m--> 210\u001b[0m     \u001b[39mraise\u001b[39;00m NameResolutionError(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mhost, \u001b[39mself\u001b[39m, e) \u001b[39mfrom\u001b[39;00m \u001b[39me\u001b[39;00m\n\u001b[0;32m    211\u001b[0m \u001b[39mexcept\u001b[39;00m SocketTimeout \u001b[39mas\u001b[39;00m e:\n",
      "\u001b[1;31mNameResolutionError\u001b[0m: <urllib3.connection.HTTPConnection object at 0x0000026A8D75F220>: Failed to resolve 'api.openweathermap.org' ([Errno 11001] getaddrinfo failed)",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[1;31mMaxRetryError\u001b[0m                             Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\adapters.py:486\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[1;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[0;32m    485\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 486\u001b[0m     resp \u001b[39m=\u001b[39m conn\u001b[39m.\u001b[39;49murlopen(\n\u001b[0;32m    487\u001b[0m         method\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mmethod,\n\u001b[0;32m    488\u001b[0m         url\u001b[39m=\u001b[39;49murl,\n\u001b[0;32m    489\u001b[0m         body\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mbody,\n\u001b[0;32m    490\u001b[0m         headers\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mheaders,\n\u001b[0;32m    491\u001b[0m         redirect\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[0;32m    492\u001b[0m         assert_same_host\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[0;32m    493\u001b[0m         preload_content\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[0;32m    494\u001b[0m         decode_content\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[0;32m    495\u001b[0m         retries\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mmax_retries,\n\u001b[0;32m    496\u001b[0m         timeout\u001b[39m=\u001b[39;49mtimeout,\n\u001b[0;32m    497\u001b[0m         chunked\u001b[39m=\u001b[39;49mchunked,\n\u001b[0;32m    498\u001b[0m     )\n\u001b[0;32m    500\u001b[0m \u001b[39mexcept\u001b[39;00m (ProtocolError, \u001b[39mOSError\u001b[39;00m) \u001b[39mas\u001b[39;00m err:\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py:844\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)\u001b[0m\n\u001b[0;32m    842\u001b[0m     new_e \u001b[39m=\u001b[39m ProtocolError(\u001b[39m\"\u001b[39m\u001b[39mConnection aborted.\u001b[39m\u001b[39m\"\u001b[39m, new_e)\n\u001b[1;32m--> 844\u001b[0m retries \u001b[39m=\u001b[39m retries\u001b[39m.\u001b[39;49mincrement(\n\u001b[0;32m    845\u001b[0m     method, url, error\u001b[39m=\u001b[39;49mnew_e, _pool\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m, _stacktrace\u001b[39m=\u001b[39;49msys\u001b[39m.\u001b[39;49mexc_info()[\u001b[39m2\u001b[39;49m]\n\u001b[0;32m    846\u001b[0m )\n\u001b[0;32m    847\u001b[0m retries\u001b[39m.\u001b[39msleep()\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\urllib3\\util\\retry.py:515\u001b[0m, in \u001b[0;36mRetry.increment\u001b[1;34m(self, method, url, response, error, _pool, _stacktrace)\u001b[0m\n\u001b[0;32m    514\u001b[0m     reason \u001b[39m=\u001b[39m error \u001b[39mor\u001b[39;00m ResponseError(cause)\n\u001b[1;32m--> 515\u001b[0m     \u001b[39mraise\u001b[39;00m MaxRetryError(_pool, url, reason) \u001b[39mfrom\u001b[39;00m \u001b[39mreason\u001b[39;00m  \u001b[39m# type: ignore[arg-type]\u001b[39;00m\n\u001b[0;32m    517\u001b[0m log\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mIncremented Retry for (url=\u001b[39m\u001b[39m'\u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m): \u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m\"\u001b[39m, url, new_retry)\n",
      "\u001b[1;31mMaxRetryError\u001b[0m: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?q=Hanoi,VN&appid=0706188be46c52e0136e9007e8e727d6 (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x0000026A8D75F220>: Failed to resolve 'api.openweathermap.org' ([Errno 11001] getaddrinfo failed)\"))",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mConnectionError\u001b[0m                           Traceback (most recent call last)",
      "\u001b[1;32md:\\Project\\NLP\\a.ipynb Cell 1\u001b[0m line \u001b[0;36m4\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/Project/NLP/a.ipynb#W0sZmlsZQ%3D%3D?line=36'>37</a>\u001b[0m         \u001b[39mprint\u001b[39m(\u001b[39m\"\u001b[39m\u001b[39mStopped streaming data\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/Project/NLP/a.ipynb#W0sZmlsZQ%3D%3D?line=38'>39</a>\u001b[0m \u001b[39m# Gọi hàm stream_weather_data với khoảng thời gian 60 giây giữa các yêu cầu\u001b[39;00m\n\u001b[1;32m---> <a href='vscode-notebook-cell:/d%3A/Project/NLP/a.ipynb#W0sZmlsZQ%3D%3D?line=39'>40</a>\u001b[0m stream_weather_data(\u001b[39m180\u001b[39;49m)\n",
      "\u001b[1;32md:\\Project\\NLP\\a.ipynb Cell 1\u001b[0m line \u001b[0;36m3\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/Project/NLP/a.ipynb#W0sZmlsZQ%3D%3D?line=31'>32</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/Project/NLP/a.ipynb#W0sZmlsZQ%3D%3D?line=32'>33</a>\u001b[0m     \u001b[39mwhile\u001b[39;00m \u001b[39mTrue\u001b[39;00m:\n\u001b[1;32m---> <a href='vscode-notebook-cell:/d%3A/Project/NLP/a.ipynb#W0sZmlsZQ%3D%3D?line=33'>34</a>\u001b[0m         get_weather_data()\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/Project/NLP/a.ipynb#W0sZmlsZQ%3D%3D?line=34'>35</a>\u001b[0m         time\u001b[39m.\u001b[39msleep(interval)  \u001b[39m# Chờ đợi khoảng thời gian trước khi gửi yêu cầu tiếp theo\u001b[39;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/Project/NLP/a.ipynb#W0sZmlsZQ%3D%3D?line=35'>36</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mKeyboardInterrupt\u001b[39;00m:\n",
      "\u001b[1;32md:\\Project\\NLP\\a.ipynb Cell 1\u001b[0m line \u001b[0;36m1\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/Project/NLP/a.ipynb#W0sZmlsZQ%3D%3D?line=12'>13</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mget_weather_data\u001b[39m():\n\u001b[1;32m---> <a href='vscode-notebook-cell:/d%3A/Project/NLP/a.ipynb#W0sZmlsZQ%3D%3D?line=13'>14</a>\u001b[0m     response \u001b[39m=\u001b[39m requests\u001b[39m.\u001b[39;49mget(complete_url)\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/Project/NLP/a.ipynb#W0sZmlsZQ%3D%3D?line=15'>16</a>\u001b[0m     \u001b[39mif\u001b[39;00m response\u001b[39m.\u001b[39mstatus_code \u001b[39m==\u001b[39m \u001b[39m200\u001b[39m:\n\u001b[0;32m     <a href='vscode-notebook-cell:/d%3A/Project/NLP/a.ipynb#W0sZmlsZQ%3D%3D?line=16'>17</a>\u001b[0m         weather_data \u001b[39m=\u001b[39m response\u001b[39m.\u001b[39mjson()\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\api.py:73\u001b[0m, in \u001b[0;36mget\u001b[1;34m(url, params, **kwargs)\u001b[0m\n\u001b[0;32m     62\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mget\u001b[39m(url, params\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[0;32m     63\u001b[0m \u001b[39m    \u001b[39m\u001b[39mr\u001b[39m\u001b[39m\"\"\"Sends a GET request.\u001b[39;00m\n\u001b[0;32m     64\u001b[0m \n\u001b[0;32m     65\u001b[0m \u001b[39m    :param url: URL for the new :class:`Request` object.\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     70\u001b[0m \u001b[39m    :rtype: requests.Response\u001b[39;00m\n\u001b[0;32m     71\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[1;32m---> 73\u001b[0m     \u001b[39mreturn\u001b[39;00m request(\u001b[39m\"\u001b[39m\u001b[39mget\u001b[39m\u001b[39m\"\u001b[39m, url, params\u001b[39m=\u001b[39mparams, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\api.py:59\u001b[0m, in \u001b[0;36mrequest\u001b[1;34m(method, url, **kwargs)\u001b[0m\n\u001b[0;32m     55\u001b[0m \u001b[39m# By using the 'with' statement we are sure the session is closed, thus we\u001b[39;00m\n\u001b[0;32m     56\u001b[0m \u001b[39m# avoid leaving sockets open which can trigger a ResourceWarning in some\u001b[39;00m\n\u001b[0;32m     57\u001b[0m \u001b[39m# cases, and look like a memory leak in others.\u001b[39;00m\n\u001b[0;32m     58\u001b[0m \u001b[39mwith\u001b[39;00m sessions\u001b[39m.\u001b[39mSession() \u001b[39mas\u001b[39;00m session:\n\u001b[1;32m---> 59\u001b[0m     \u001b[39mreturn\u001b[39;00m session\u001b[39m.\u001b[39mrequest(method\u001b[39m=\u001b[39mmethod, url\u001b[39m=\u001b[39murl, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\sessions.py:589\u001b[0m, in \u001b[0;36mSession.request\u001b[1;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[0;32m    584\u001b[0m send_kwargs \u001b[39m=\u001b[39m {\n\u001b[0;32m    585\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mtimeout\u001b[39m\u001b[39m\"\u001b[39m: timeout,\n\u001b[0;32m    586\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mallow_redirects\u001b[39m\u001b[39m\"\u001b[39m: allow_redirects,\n\u001b[0;32m    587\u001b[0m }\n\u001b[0;32m    588\u001b[0m send_kwargs\u001b[39m.\u001b[39mupdate(settings)\n\u001b[1;32m--> 589\u001b[0m resp \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msend(prep, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39msend_kwargs)\n\u001b[0;32m    591\u001b[0m \u001b[39mreturn\u001b[39;00m resp\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\sessions.py:703\u001b[0m, in \u001b[0;36mSession.send\u001b[1;34m(self, request, **kwargs)\u001b[0m\n\u001b[0;32m    700\u001b[0m start \u001b[39m=\u001b[39m preferred_clock()\n\u001b[0;32m    702\u001b[0m \u001b[39m# Send the request\u001b[39;00m\n\u001b[1;32m--> 703\u001b[0m r \u001b[39m=\u001b[39m adapter\u001b[39m.\u001b[39msend(request, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[0;32m    705\u001b[0m \u001b[39m# Total elapsed time of the request (approximately)\u001b[39;00m\n\u001b[0;32m    706\u001b[0m elapsed \u001b[39m=\u001b[39m preferred_clock() \u001b[39m-\u001b[39m start\n",
      "File \u001b[1;32mc:\\Users\\Windows\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\adapters.py:519\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[1;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[0;32m    515\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(e\u001b[39m.\u001b[39mreason, _SSLError):\n\u001b[0;32m    516\u001b[0m         \u001b[39m# This branch is for urllib3 v1.22 and later.\u001b[39;00m\n\u001b[0;32m    517\u001b[0m         \u001b[39mraise\u001b[39;00m SSLError(e, request\u001b[39m=\u001b[39mrequest)\n\u001b[1;32m--> 519\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mConnectionError\u001b[39;00m(e, request\u001b[39m=\u001b[39mrequest)\n\u001b[0;32m    521\u001b[0m \u001b[39mexcept\u001b[39;00m ClosedPoolError \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m    522\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mConnectionError\u001b[39;00m(e, request\u001b[39m=\u001b[39mrequest)\n",
      "\u001b[1;31mConnectionError\u001b[0m: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /data/2.5/weather?q=Hanoi,VN&appid=0706188be46c52e0136e9007e8e727d6 (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x0000026A8D75F220>: Failed to resolve 'api.openweathermap.org' ([Errno 11001] getaddrinfo failed)\"))"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import time\n",
    "\n",
    "# API key của bạn\n",
    "api_key = \"0706188be46c52e0136e9007e8e727d6\"\n",
    "city_name = \"Hanoi\"\n",
    "country_code = \"VN\"  # Mã quốc gia (VN cho Việt Nam)\n",
    "base_url = \"http://api.openweathermap.org/data/2.5/weather?\"\n",
    "\n",
    "# Tạo URL để thực hiện yêu cầu\n",
    "complete_url = f\"{base_url}q={city_name},{country_code}&appid={api_key}\"\n",
    "\n",
    "def get_weather_data():\n",
    "    response = requests.get(complete_url)\n",
    "    \n",
    "    if response.status_code == 200:\n",
    "        weather_data = response.json()\n",
    "        main = weather_data[\"main\"]\n",
    "        wind = weather_data[\"wind\"]\n",
    "        weather_description = weather_data[\"weather\"][0][\"description\"]\n",
    "\n",
    "        print(f\"Temperature: {main['temp'] - 273.15:.2f}°C\")\n",
    "        print(f\"Pressure: {main['pressure']} hPa\")\n",
    "        print(f\"Humidity: {main['humidity']}%\")\n",
    "        print(f\"Description: {weather_description}\")\n",
    "        print(f\"Wind Speed: {wind['speed']} m/s\")\n",
    "    else:\n",
    "        print(f\"City not found or there was an error: {response.status_code}\")\n",
    "\n",
    "# Streaming dữ liệu liên tục với khoảng thời gian giữa các yêu cầu\n",
    "def stream_weather_data(interval=60):\n",
    "    try:\n",
    "        while True:\n",
    "            get_weather_data()\n",
    "            time.sleep(interval)  # Chờ đợi khoảng thời gian trước khi gửi yêu cầu tiếp theo\n",
    "    except KeyboardInterrupt:\n",
    "        print(\"Stopped streaming data\")\n",
    "\n",
    "# Gọi hàm stream_weather_data với khoảng thời gian 60 giây giữa các yêu cầu\n",
    "stream_weather_data(180)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Temperature: 29.00°C\n",
      "Pressure: 1003 hPa\n",
      "Humidity: 78%\n",
      "Description: overcast clouds\n",
      "Wind Speed: 4.97 m/s\n"
     ]
    }
   ],
   "source": [
    "api_key = \"0706188be46c52e0136e9007e8e727d6\"\n",
    "city_name = \"Hanoi\"\n",
    "country_code = \"VN\"  # Mã quốc gia (VN cho Việt Nam)\n",
    "base_url = \"http://api.openweathermap.org/data/2.5/weather?\"\n",
    "\n",
    "# Tạo URL để thực hiện yêu cầu\n",
    "complete_url = f\"{base_url}q={city_name},{country_code}&appid={api_key}\"\n",
    "\n",
    "def get_weather_data():\n",
    "    response = requests.get(complete_url)\n",
    "    \n",
    "    if response.status_code == 200:\n",
    "        weather_data = response.json()\n",
    "        main = weather_data[\"main\"]\n",
    "        wind = weather_data[\"wind\"]\n",
    "        weather_description = weather_data[\"weather\"][0][\"description\"]\n",
    "\n",
    "        print(f\"Temperature: {main['temp'] - 273.15:.2f}°C\")\n",
    "        print(f\"Pressure: {main['pressure']} hPa\")\n",
    "        print(f\"Humidity: {main['humidity']}%\")\n",
    "        print(f\"Description: {weather_description}\")\n",
    "        print(f\"Wind Speed: {wind['speed']} m/s\")\n",
    "    else:\n",
    "        print(f\"City not found or there was an error: {response.status_code}\")\n",
    "\n",
    "# Streaming dữ liệu liên tục với khoảng thời gian giữa các yêu cầu\n",
    "get_weather_data()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "HTTP Status Code: 200\n",
      "Response Content: {\"coord\":{\"lon\":105.8412,\"lat\":21.0245},\"weather\":[{\"id\":804,\"main\":\"Clouds\",\"description\":\"overcast clouds\",\"icon\":\"04d\"}],\"base\":\"stations\",\"main\":{\"temp\":302.15,\"feels_like\":307.46,\"temp_min\":302.15,\"temp_max\":302.15,\"pressure\":1003,\"humidity\":78,\"sea_level\":1003,\"grnd_level\":1001},\"visibility\":10000,\"wind\":{\"speed\":4.97,\"deg\":141,\"gust\":8.58},\"clouds\":{\"all\":100},\"dt\":1721473064,\"sys\":{\"type\":1,\"id\":9308,\"country\":\"VN\",\"sunrise\":1721427940,\"sunset\":1721475596},\"timezone\":25200,\"id\":1581130,\"name\":\"Hanoi\",\"cod\":200}\n",
      "Temperature: 29.00°C\n",
      "Pressure: 1003 hPa\n",
      "Humidity: 78%\n",
      "Description: overcast clouds\n",
      "Wind Speed: 4.97 m/s\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "\n",
    "# API key của bạn\n",
    "api_key = \"0706188be46c52e0136e9007e8e727d6\"\n",
    "city_name = \"Hanoi\"\n",
    "country_code = \"VN\"  # Mã quốc gia (VN cho Việt Nam)\n",
    "base_url = \"http://api.openweathermap.org/data/2.5/weather?\"\n",
    "\n",
    "# Tạo URL để thực hiện yêu cầu\n",
    "complete_url = f\"{base_url}q={city_name},{country_code}&appid={api_key}\"\n",
    "\n",
    "# Gửi yêu cầu và nhận phản hồi\n",
    "response = requests.get(complete_url)\n",
    "\n",
    "# Kiểm tra mã trạng thái HTTP và nội dung phản hồi\n",
    "print(f\"HTTP Status Code: {response.status_code}\")\n",
    "print(f\"Response Content: {response.content.decode('utf-8')}\")\n",
    "\n",
    "# Nếu thành công, phân tích và in dữ liệu thời tiết\n",
    "if response.status_code == 200:\n",
    "    weather_data = response.json()\n",
    "    main = weather_data[\"main\"]\n",
    "    wind = weather_data[\"wind\"]\n",
    "    weather_description = weather_data[\"weather\"][0][\"description\"]\n",
    "\n",
    "    print(f\"Temperature: {main['temp'] - 273.15:.2f}°C\")\n",
    "    print(f\"Pressure: {main['pressure']} hPa\")\n",
    "    print(f\"Humidity: {main['humidity']}%\")\n",
    "    print(f\"Description: {weather_description}\")\n",
    "    print(f\"Wind Speed: {wind['speed']} m/s\")\n",
    "else:\n",
    "    print(f\"City not found or there was an error: {response.status_code}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{\n",
      "    \"Temperature\": 28.0,\n",
      "    \"Pressure\": 1006,\n",
      "    \"Humidity\": 89,\n",
      "    \"Description\": \"overcast clouds\",\n",
      "    \"Wind Speed\": 2.62,\n",
      "    \"Timestamp\": \"2024-07-20T22:50:08.747204\"\n",
      "}\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import time\n",
    "import json\n",
    "from datetime import datetime\n",
    "\n",
    "# API key của bạn\n",
    "api_key = \"0706188be46c52e0136e9007e8e727d6\"\n",
    "city_name = \"Hanoi\"\n",
    "country_code = \"VN\"  # Mã quốc gia (VN cho Việt Nam)\n",
    "base_url = \"http://api.openweathermap.org/data/2.5/weather?\"\n",
    "\n",
    "# Tạo URL để thực hiện yêu cầu\n",
    "complete_url = f\"{base_url}q={city_name},{country_code}&appid={api_key}\"\n",
    "\n",
    "def get_weather_data():\n",
    "    response = requests.get(complete_url)\n",
    "    \n",
    "    if response.status_code == 200:\n",
    "        weather_data = response.json()\n",
    "        main = weather_data[\"main\"]\n",
    "        wind = weather_data[\"wind\"]\n",
    "        weather_description = weather_data[\"weather\"][0][\"description\"]\n",
    "\n",
    "        weather_info = {\n",
    "            \"Temperature\": main['temp'] - 273.15,\n",
    "            \"Pressure\": main['pressure'],\n",
    "            \"Humidity\": main['humidity'],\n",
    "            \"Description\": weather_description,\n",
    "            \"Wind Speed\": wind['speed'],\n",
    "            \"Timestamp\": datetime.now().isoformat()\n",
    "        }\n",
    "        \n",
    "        print(json.dumps(weather_info, indent=4))\n",
    "        \n",
    "        # Lưu dữ liệu vào tệp JSON\n",
    "        file_name = f\"weather_data_{datetime.now().strftime('%Y%m%d%H%M%S')}.json\"\n",
    "        with open(file_name, 'w') as json_file:\n",
    "            json.dump(weather_info, json_file, indent=4)\n",
    "    else:\n",
    "        print(f\"City not found or there was an error: {response.status_code}\")\n",
    "\n",
    "# Streaming dữ liệu liên tục với khoảng thời gian giữa các yêu cầu\n",
    "def stream_weather_data(interval=60):\n",
    "    try:\n",
    "        while True:\n",
    "            get_weather_data()\n",
    "            time.sleep(interval)  # Chờ đợi khoảng thời gian trước khi gửi yêu cầu tiếp theo\n",
    "    except KeyboardInterrupt:\n",
    "        print(\"Stopped streaming data\")\n",
    "\n",
    "# Gọi hàm stream_weather_data với khoảng thời gian 60 giây giữa các yêu cầu\n",
    "get_weather_data()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: tensorflow in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (2.15.0)"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip is available: 24.1.1 -> 24.1.2\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Requirement already satisfied: tensorflow-intel==2.15.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow) (2.15.0)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.1.0)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.6.3)\n",
      "Requirement already satisfied: flatbuffers>=23.5.26 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (23.5.26)\n",
      "Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.5.4)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.2.0)\n",
      "Requirement already satisfied: h5py>=2.9.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.10.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (16.0.6)\n",
      "Requirement already satisfied: ml-dtypes~=0.2.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.2.0)\n",
      "Requirement already satisfied: numpy<2.0.0,>=1.23.5 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.23.5)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.3.0)\n",
      "Requirement already satisfied: packaging in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (23.1)\n",
      "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (4.25.3)\n",
      "Requirement already satisfied: setuptools in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (57.4.0)\n",
      "Requirement already satisfied: six>=1.12.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.16.0)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.4.0)\n",
      "Requirement already satisfied: typing-extensions>=3.6.6 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (4.10.0)\n",
      "Requirement already satisfied: wrapt<1.15,>=1.11.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.14.1)\n",
      "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.31.0)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.62.0)\n",
      "Requirement already satisfied: tensorboard<2.16,>=2.15 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.2)\n",
      "Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.0)\n",
      "Requirement already satisfied: keras<2.16,>=2.15.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.0)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.15.0->tensorflow) (0.42.0)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.28.1)\n",
      "Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (1.2.0)\n",
      "Requirement already satisfied: markdown>=2.6.8 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.5.2)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.31.0)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (0.7.2)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.0.1)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (5.3.3)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (0.3.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (4.9)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (1.3.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.2.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.0.5)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2023.7.22)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.1.3)\n",
      "Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (0.5.1)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in c:\\users\\windows\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.2.2)\n"
     ]
    }
   ],
   "source": [
    "! pip install tensorflow "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{\n",
      "    \"coord\": {\n",
      "        \"lon\": 105.8412,\n",
      "        \"lat\": 21.0245\n",
      "    },\n",
      "    \"weather\": [\n",
      "        {\n",
      "            \"id\": 804,\n",
      "            \"main\": \"Clouds\",\n",
      "            \"description\": \"overcast clouds\",\n",
      "            \"icon\": \"04n\"\n",
      "        }\n",
      "    ],\n",
      "    \"base\": \"stations\",\n",
      "    \"main\": {\n",
      "        \"temp\": 301.15,\n",
      "        \"feels_like\": 306.72,\n",
      "        \"temp_min\": 301.15,\n",
      "        \"temp_max\": 301.15,\n",
      "        \"pressure\": 1006,\n",
      "        \"humidity\": 89,\n",
      "        \"sea_level\": 1006,\n",
      "        \"grnd_level\": 1005\n",
      "    },\n",
      "    \"visibility\": 10000,\n",
      "    \"wind\": {\n",
      "        \"speed\": 2.62,\n",
      "        \"deg\": 136,\n",
      "        \"gust\": 6.87\n",
      "    },\n",
      "    \"clouds\": {\n",
      "        \"all\": 100\n",
      "    },\n",
      "    \"dt\": 1721490593,\n",
      "    \"sys\": {\n",
      "        \"type\": 1,\n",
      "        \"id\": 9308,\n",
      "        \"country\": \"VN\",\n",
      "        \"sunrise\": 1721427940,\n",
      "        \"sunset\": 1721475596\n",
      "    },\n",
      "    \"timezone\": 25200,\n",
      "    \"id\": 1581130,\n",
      "    \"name\": \"Hanoi\",\n",
      "    \"cod\": 200\n",
      "}\n",
      "HTTP Status Code: 200\n",
      "Response Content: {\"coord\":{\"lon\":105.8412,\"lat\":21.0245},\"weather\":[{\"id\":804,\"main\":\"Clouds\",\"description\":\"overcast clouds\",\"icon\":\"04n\"}],\"base\":\"stations\",\"main\":{\"temp\":301.15,\"feels_like\":306.72,\"temp_min\":301.15,\"temp_max\":301.15,\"pressure\":1006,\"humidity\":89,\"sea_level\":1006,\"grnd_level\":1005},\"visibility\":10000,\"wind\":{\"speed\":2.62,\"deg\":136,\"gust\":6.87},\"clouds\":{\"all\":100},\"dt\":1721490593,\"sys\":{\"type\":1,\"id\":9308,\"country\":\"VN\",\"sunrise\":1721427940,\"sunset\":1721475596},\"timezone\":25200,\"id\":1581130,\"name\":\"Hanoi\",\"cod\":200}\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "\n",
    "api_key = \"0706188be46c52e0136e9007e8e727d6\"\n",
    "city_name = \"Hanoi\"\n",
    "country_code = \"VN\"\n",
    "base_url = \"http://api.openweathermap.org/data/2.5/weather\"\n",
    "\n",
    "complete_url = f\"{base_url}?q={city_name},{country_code}&appid={api_key}\"\n",
    "\n",
    "response = requests.get(complete_url)\n",
    "\n",
    "\n",
    "print(f\"HTTP Status Code: {response.status_code}\")\n",
    "print(f\"Response Content: {response.content.decode('utf-8')}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error 401 for 2022-01-01\n",
      "Error 401 for 2022-01-02\n",
      "Error 401 for 2022-01-03\n",
      "Error 401 for 2022-01-04\n",
      "Error 401 for 2022-01-05\n",
      "Error 401 for 2022-01-06\n",
      "Error 401 for 2022-01-07\n",
      "Error 401 for 2022-01-08\n",
      "Error 401 for 2022-01-09\n",
      "Error 401 for 2022-01-10\n",
      "Error 401 for 2022-01-11\n",
      "Error 401 for 2022-01-12\n",
      "Error 401 for 2022-01-13\n",
      "Error 401 for 2022-01-14\n",
      "Error 401 for 2022-01-15\n",
      "Error 401 for 2022-01-16\n",
      "Error 401 for 2022-01-17\n",
      "Error 401 for 2022-01-18\n",
      "Error 401 for 2022-01-19\n",
      "Error 401 for 2022-01-20\n",
      "Error 401 for 2022-01-21\n",
      "Error 401 for 2022-01-22\n",
      "Error 401 for 2022-01-23\n",
      "Error 401 for 2022-01-24\n",
      "Error 401 for 2022-01-25\n",
      "Error 401 for 2022-01-26\n",
      "Error 401 for 2022-01-27\n",
      "Error 401 for 2022-01-28\n",
      "Error 401 for 2022-01-29\n",
      "Error 401 for 2022-01-30\n",
      "Error 401 for 2022-01-31\n",
      "Error 401 for 2022-02-01\n",
      "Error 401 for 2022-02-02\n",
      "Error 401 for 2022-02-03\n",
      "Error 401 for 2022-02-04\n",
      "Error 401 for 2022-02-05\n",
      "Error 401 for 2022-02-06\n",
      "Error 401 for 2022-02-07\n",
      "Error 401 for 2022-02-08\n",
      "Error 401 for 2022-02-09\n",
      "Error 401 for 2022-02-10\n",
      "Error 401 for 2022-02-11\n",
      "Error 401 for 2022-02-12\n",
      "Error 401 for 2022-02-13\n",
      "Error 401 for 2022-02-14\n",
      "Error 401 for 2022-02-15\n",
      "Error 401 for 2022-02-16\n",
      "Error 401 for 2022-02-17\n",
      "Error 401 for 2022-02-18\n",
      "Error 401 for 2022-02-19\n",
      "Error 401 for 2022-02-20\n",
      "Error 401 for 2022-02-21\n",
      "Error 401 for 2022-02-22\n",
      "Error 401 for 2022-02-23\n",
      "Error 401 for 2022-02-24\n",
      "Error 401 for 2022-02-25\n",
      "Error 401 for 2022-02-26\n",
      "Error 401 for 2022-02-27\n",
      "Error 401 for 2022-02-28\n",
      "Error 401 for 2022-03-01\n",
      "Error 401 for 2022-03-02\n",
      "Error 401 for 2022-03-03\n",
      "Error 401 for 2022-03-04\n",
      "Error 401 for 2022-03-05\n",
      "Error 401 for 2022-03-06\n",
      "Error 401 for 2022-03-07\n",
      "Error 401 for 2022-03-08\n",
      "Error 401 for 2022-03-09\n",
      "Error 401 for 2022-03-10\n",
      "Error 401 for 2022-03-11\n",
      "Error 401 for 2022-03-12\n",
      "Error 401 for 2022-03-13\n",
      "Error 401 for 2022-03-14\n",
      "Error 401 for 2022-03-15\n",
      "Error 401 for 2022-03-16\n",
      "Error 401 for 2022-03-17\n",
      "Error 401 for 2022-03-18\n",
      "Error 401 for 2022-03-19\n",
      "Error 401 for 2022-03-20\n",
      "Error 401 for 2022-03-21\n",
      "Error 401 for 2022-03-22\n",
      "Error 401 for 2022-03-23\n",
      "Error 401 for 2022-03-24\n",
      "Error 401 for 2022-03-25\n",
      "Error 401 for 2022-03-26\n",
      "Error 401 for 2022-03-27\n",
      "Error 401 for 2022-03-28\n",
      "Error 401 for 2022-03-29\n",
      "Error 401 for 2022-03-30\n",
      "Error 401 for 2022-03-31\n",
      "Error 401 for 2022-04-01\n",
      "Error 401 for 2022-04-02\n",
      "Error 401 for 2022-04-03\n",
      "Error 401 for 2022-04-04\n",
      "Error 401 for 2022-04-05\n",
      "Error 401 for 2022-04-06\n",
      "Error 401 for 2022-04-07\n",
      "Error 401 for 2022-04-08\n",
      "Error 401 for 2022-04-09\n",
      "Error 401 for 2022-04-10\n",
      "Error 401 for 2022-04-11\n",
      "Error 401 for 2022-04-12\n",
      "Error 401 for 2022-04-13\n",
      "Error 401 for 2022-04-14\n",
      "Error 401 for 2022-04-15\n",
      "Error 401 for 2022-04-16\n",
      "Error 401 for 2022-04-17\n",
      "Error 401 for 2022-04-18\n",
      "Error 401 for 2022-04-19\n",
      "Error 401 for 2022-04-20\n",
      "Error 401 for 2022-04-21\n",
      "Error 401 for 2022-04-22\n",
      "Error 401 for 2022-04-23\n",
      "Error 401 for 2022-04-24\n",
      "Error 401 for 2022-04-25\n",
      "Error 401 for 2022-04-26\n",
      "Error 401 for 2022-04-27\n",
      "Error 401 for 2022-04-28\n",
      "Error 401 for 2022-04-29\n",
      "Error 401 for 2022-04-30\n",
      "Error 401 for 2022-05-01\n",
      "Error 401 for 2022-05-02\n",
      "Error 401 for 2022-05-03\n",
      "Error 401 for 2022-05-04\n",
      "Error 401 for 2022-05-05\n",
      "Error 401 for 2022-05-06\n",
      "Error 401 for 2022-05-07\n",
      "Error 401 for 2022-05-08\n",
      "Error 401 for 2022-05-09\n",
      "Error 401 for 2022-05-10\n",
      "Error 401 for 2022-05-11\n",
      "Error 401 for 2022-05-12\n",
      "Error 401 for 2022-05-13\n",
      "Error 401 for 2022-05-14\n",
      "Error 401 for 2022-05-15\n",
      "Error 401 for 2022-05-16\n",
      "Error 401 for 2022-05-17\n",
      "Error 401 for 2022-05-18\n",
      "Error 401 for 2022-05-19\n",
      "Error 401 for 2022-05-20\n",
      "Error 401 for 2022-05-21\n",
      "Error 401 for 2022-05-22\n",
      "Error 401 for 2022-05-23\n",
      "Error 401 for 2022-05-24\n",
      "Error 401 for 2022-05-25\n",
      "Error 401 for 2022-05-26\n",
      "Error 401 for 2022-05-27\n",
      "Error 401 for 2022-05-28\n",
      "Error 401 for 2022-05-29\n",
      "Error 401 for 2022-05-30\n",
      "Error 401 for 2022-05-31\n",
      "Error 401 for 2022-06-01\n",
      "Error 401 for 2022-06-02\n",
      "Error 401 for 2022-06-03\n",
      "Error 401 for 2022-06-04\n",
      "Error 401 for 2022-06-05\n",
      "Error 401 for 2022-06-06\n",
      "Error 401 for 2022-06-07\n",
      "Error 401 for 2022-06-08\n",
      "Error 401 for 2022-06-09\n",
      "Error 401 for 2022-06-10\n",
      "Error 401 for 2022-06-11\n",
      "Error 401 for 2022-06-12\n",
      "Error 401 for 2022-06-13\n",
      "Error 401 for 2022-06-14\n",
      "Error 401 for 2022-06-15\n",
      "Error 401 for 2022-06-16\n",
      "Error 401 for 2022-06-17\n",
      "Error 401 for 2022-06-18\n",
      "Error 401 for 2022-06-19\n",
      "Error 401 for 2022-06-20\n",
      "Error 401 for 2022-06-21\n",
      "Error 401 for 2022-06-22\n",
      "Error 401 for 2022-06-23\n",
      "Error 401 for 2022-06-24\n",
      "Error 401 for 2022-06-25\n",
      "Error 401 for 2022-06-26\n",
      "Error 401 for 2022-06-27\n",
      "Error 401 for 2022-06-28\n",
      "Error 401 for 2022-06-29\n",
      "Error 401 for 2022-06-30\n",
      "Error 401 for 2022-07-01\n",
      "Error 401 for 2022-07-02\n",
      "Error 401 for 2022-07-03\n",
      "Error 401 for 2022-07-04\n",
      "Error 401 for 2022-07-05\n",
      "Error 401 for 2022-07-06\n",
      "Error 401 for 2022-07-07\n",
      "Error 401 for 2022-07-08\n",
      "Error 401 for 2022-07-09\n",
      "Error 401 for 2022-07-10\n",
      "Error 401 for 2022-07-11\n",
      "Error 401 for 2022-07-12\n",
      "Error 401 for 2022-07-13\n",
      "Error 401 for 2022-07-14\n",
      "Error 401 for 2022-07-15\n",
      "Error 401 for 2022-07-16\n",
      "Error 401 for 2022-07-17\n",
      "Error 401 for 2022-07-18\n",
      "Error 401 for 2022-07-19\n",
      "Error 401 for 2022-07-20\n",
      "Error 401 for 2022-07-21\n",
      "Error 401 for 2022-07-22\n",
      "Error 401 for 2022-07-23\n",
      "Error 401 for 2022-07-24\n",
      "Error 401 for 2022-07-25\n",
      "Error 401 for 2022-07-26\n",
      "Error 401 for 2022-07-27\n",
      "Error 401 for 2022-07-28\n",
      "Error 401 for 2022-07-29\n",
      "Error 401 for 2022-07-30\n",
      "Error 401 for 2022-07-31\n",
      "Error 401 for 2022-08-01\n",
      "Error 401 for 2022-08-02\n",
      "Error 401 for 2022-08-03\n",
      "Error 401 for 2022-08-04\n",
      "Error 401 for 2022-08-05\n",
      "Error 401 for 2022-08-06\n",
      "Error 401 for 2022-08-07\n",
      "Error 401 for 2022-08-08\n",
      "Error 401 for 2022-08-09\n",
      "Error 401 for 2022-08-10\n",
      "Error 401 for 2022-08-11\n",
      "Error 401 for 2022-08-12\n",
      "Error 401 for 2022-08-13\n",
      "Error 401 for 2022-08-14\n",
      "Error 401 for 2022-08-15\n",
      "Error 401 for 2022-08-16\n",
      "Error 401 for 2022-08-17\n",
      "Error 401 for 2022-08-18\n",
      "Error 401 for 2022-08-19\n",
      "Error 401 for 2022-08-20\n",
      "Error 401 for 2022-08-21\n",
      "Error 401 for 2022-08-22\n",
      "Error 401 for 2022-08-23\n",
      "Error 401 for 2022-08-24\n",
      "Error 401 for 2022-08-25\n",
      "Error 401 for 2022-08-26\n",
      "Error 401 for 2022-08-27\n",
      "Error 401 for 2022-08-28\n",
      "Error 401 for 2022-08-29\n",
      "Error 401 for 2022-08-30\n",
      "Error 401 for 2022-08-31\n",
      "Error 401 for 2022-09-01\n",
      "Error 401 for 2022-09-02\n",
      "Error 401 for 2022-09-03\n",
      "Error 401 for 2022-09-04\n",
      "Error 401 for 2022-09-05\n",
      "Error 401 for 2022-09-06\n",
      "Error 401 for 2022-09-07\n",
      "Error 401 for 2022-09-08\n",
      "Error 401 for 2022-09-09\n",
      "Error 401 for 2022-09-10\n",
      "Error 401 for 2022-09-11\n",
      "Error 401 for 2022-09-12\n",
      "Error 401 for 2022-09-13\n",
      "Error 401 for 2022-09-14\n",
      "Error 401 for 2022-09-15\n",
      "Error 401 for 2022-09-16\n",
      "Error 401 for 2022-09-17\n",
      "Error 401 for 2022-09-18\n",
      "Error 401 for 2022-09-19\n",
      "Error 401 for 2022-09-20\n",
      "Error 401 for 2022-09-21\n",
      "Error 401 for 2022-09-22\n",
      "Error 401 for 2022-09-23\n",
      "Error 401 for 2022-09-24\n",
      "Error 401 for 2022-09-25\n",
      "Error 401 for 2022-09-26\n",
      "Error 401 for 2022-09-27\n",
      "Error 401 for 2022-09-28\n",
      "Error 401 for 2022-09-29\n",
      "Error 401 for 2022-09-30\n",
      "Error 401 for 2022-10-01\n",
      "Error 401 for 2022-10-02\n",
      "Error 401 for 2022-10-03\n",
      "Error 401 for 2022-10-04\n",
      "Error 401 for 2022-10-05\n",
      "Error 401 for 2022-10-06\n",
      "Error 401 for 2022-10-07\n",
      "Error 401 for 2022-10-08\n",
      "Error 401 for 2022-10-09\n",
      "Error 401 for 2022-10-10\n",
      "Error 401 for 2022-10-11\n",
      "Error 401 for 2022-10-12\n",
      "Error 401 for 2022-10-13\n",
      "Error 401 for 2022-10-14\n",
      "Error 401 for 2022-10-15\n",
      "Error 401 for 2022-10-16\n",
      "Error 401 for 2022-10-17\n",
      "Error 401 for 2022-10-18\n",
      "Error 401 for 2022-10-19\n",
      "Error 401 for 2022-10-20\n",
      "Error 401 for 2022-10-21\n",
      "Error 401 for 2022-10-22\n",
      "Error 401 for 2022-10-23\n",
      "Error 401 for 2022-10-24\n",
      "Error 401 for 2022-10-25\n",
      "Error 401 for 2022-10-26\n",
      "Error 401 for 2022-10-27\n",
      "Error 401 for 2022-10-28\n",
      "Error 401 for 2022-10-29\n",
      "Error 401 for 2022-10-30\n",
      "Error 401 for 2022-10-31\n",
      "Error 401 for 2022-11-01\n",
      "Error 401 for 2022-11-02\n",
      "Error 401 for 2022-11-03\n",
      "Error 401 for 2022-11-04\n",
      "Error 401 for 2022-11-05\n",
      "Error 401 for 2022-11-06\n",
      "Error 401 for 2022-11-07\n",
      "Error 401 for 2022-11-08\n",
      "Error 401 for 2022-11-09\n",
      "Error 401 for 2022-11-10\n",
      "Error 401 for 2022-11-11\n",
      "Error 401 for 2022-11-12\n",
      "Error 401 for 2022-11-13\n",
      "Error 401 for 2022-11-14\n",
      "Error 401 for 2022-11-15\n",
      "Error 401 for 2022-11-16\n",
      "Error 401 for 2022-11-17\n",
      "Error 401 for 2022-11-18\n",
      "Error 401 for 2022-11-19\n",
      "Error 401 for 2022-11-20\n",
      "Error 401 for 2022-11-21\n",
      "Error 401 for 2022-11-22\n",
      "Error 401 for 2022-11-23\n",
      "Error 401 for 2022-11-24\n",
      "Error 401 for 2022-11-25\n",
      "Error 401 for 2022-11-26\n",
      "Error 401 for 2022-11-27\n",
      "Error 401 for 2022-11-28\n",
      "Error 401 for 2022-11-29\n",
      "Error 401 for 2022-11-30\n",
      "Error 401 for 2022-12-01\n",
      "Error 401 for 2022-12-02\n",
      "Error 401 for 2022-12-03\n",
      "Error 401 for 2022-12-04\n",
      "Error 401 for 2022-12-05\n",
      "Error 401 for 2022-12-06\n",
      "Error 401 for 2022-12-07\n",
      "Error 401 for 2022-12-08\n",
      "Error 401 for 2022-12-09\n",
      "Error 401 for 2022-12-10\n",
      "Error 401 for 2022-12-11\n",
      "Error 401 for 2022-12-12\n",
      "Error 401 for 2022-12-13\n",
      "Error 401 for 2022-12-14\n",
      "Error 401 for 2022-12-15\n",
      "Error 401 for 2022-12-16\n",
      "Error 401 for 2022-12-17\n",
      "Error 401 for 2022-12-18\n",
      "Error 401 for 2022-12-19\n",
      "Error 401 for 2022-12-20\n",
      "Error 401 for 2022-12-21\n",
      "Error 401 for 2022-12-22\n",
      "Error 401 for 2022-12-23\n",
      "Error 401 for 2022-12-24\n",
      "Error 401 for 2022-12-25\n",
      "Error 401 for 2022-12-26\n",
      "Error 401 for 2022-12-27\n",
      "Error 401 for 2022-12-28\n",
      "Error 401 for 2022-12-29\n",
      "Error 401 for 2022-12-30\n",
      "Error 401 for 2022-12-31\n",
      "Error 401 for 2023-01-01\n",
      "Error 401 for 2023-01-02\n",
      "Error 401 for 2023-01-03\n",
      "Error 401 for 2023-01-04\n",
      "Error 401 for 2023-01-05\n",
      "Error 401 for 2023-01-06\n",
      "Error 401 for 2023-01-07\n",
      "Error 401 for 2023-01-08\n",
      "Error 401 for 2023-01-09\n",
      "Error 401 for 2023-01-10\n",
      "Error 401 for 2023-01-11\n",
      "Error 401 for 2023-01-12\n",
      "Error 401 for 2023-01-13\n",
      "Error 401 for 2023-01-14\n",
      "Error 401 for 2023-01-15\n",
      "Error 401 for 2023-01-16\n",
      "Error 401 for 2023-01-17\n",
      "Error 401 for 2023-01-18\n",
      "Error 401 for 2023-01-19\n",
      "Error 401 for 2023-01-20\n",
      "Error 401 for 2023-01-21\n",
      "Error 401 for 2023-01-22\n",
      "Error 401 for 2023-01-23\n",
      "Error 401 for 2023-01-24\n",
      "Error 401 for 2023-01-25\n",
      "Error 401 for 2023-01-26\n",
      "Error 401 for 2023-01-27\n",
      "Error 401 for 2023-01-28\n",
      "Error 401 for 2023-01-29\n",
      "Error 401 for 2023-01-30\n",
      "Error 401 for 2023-01-31\n",
      "Error 401 for 2023-02-01\n",
      "Error 401 for 2023-02-02\n",
      "Error 401 for 2023-02-03\n",
      "Error 401 for 2023-02-04\n",
      "Error 401 for 2023-02-05\n",
      "Error 401 for 2023-02-06\n",
      "Error 401 for 2023-02-07\n",
      "Error 401 for 2023-02-08\n",
      "Error 401 for 2023-02-09\n",
      "Error 401 for 2023-02-10\n",
      "Error 401 for 2023-02-11\n",
      "Error 401 for 2023-02-12\n",
      "Error 401 for 2023-02-13\n",
      "Error 401 for 2023-02-14\n",
      "Error 401 for 2023-02-15\n",
      "Error 401 for 2023-02-16\n",
      "Error 401 for 2023-02-17\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import time\n",
    "import json\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "# API key của bạn\n",
    "api_key = \"0706188be46c52e0136e9007e8e727d6\"\n",
    "\n",
    "# Tọa độ của thành phố Hà Nội\n",
    "latitude = 21.0285\n",
    "longitude = 105.8542\n",
    "\n",
    "# Thời gian bắt đầu (ngày đầu tiên của năm 2022)\n",
    "start_date = datetime(2022, 1, 1)\n",
    "\n",
    "# Số ngày cần lấy dữ liệu\n",
    "num_days = 1000\n",
    "\n",
    "# Tạo danh sách các thời gian Unix (Epoch) cho mỗi ngày\n",
    "timestamps = [int((start_date + timedelta(days=i)).timestamp()) for i in range(num_days)]\n",
    "\n",
    "# File để lưu dữ liệu\n",
    "output_file = \"weather_data_2022_2023.txt\"\n",
    "\n",
    "# Mở file để ghi\n",
    "with open(output_file, 'w') as file:\n",
    "    for i, past_time in enumerate(timestamps):\n",
    "        # Tạo URL để thực hiện yêu cầu\n",
    "        base_url = \"http://api.openweathermap.org/data/3.0/onecall/timemachine\"\n",
    "        complete_url = f\"{base_url}?lat={latitude}&lon={longitude}&dt={past_time}&appid={api_key}\"\n",
    "        \n",
    "        # Gửi yêu cầu và nhận phản hồi\n",
    "        response = requests.get(complete_url)\n",
    "        \n",
    "        if response.status_code == 200:\n",
    "            weather_data = response.json()\n",
    "            \n",
    "            # Ghi dữ liệu vào file\n",
    "            file.write(json.dumps(weather_data) + '\\n')\n",
    "            \n",
    "            print(f\"Fetched data for {datetime.fromtimestamp(past_time).strftime('%Y-%m-%d')} (Day {i + 1} of {num_days})\")\n",
    "        else:\n",
    "            print(f\"Error {response.status_code} for {datetime.fromtimestamp(past_time).strftime('%Y-%m-%d')}\")\n",
    "        \n",
    "        # Chờ một chút để không vượt quá giới hạn tốc độ API\n",
    "        time.sleep(1)  # Điều chỉnh thời gian nghỉ dựa trên giới hạn tốc độ API của bạn\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
